spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fee-db
security:
  predefined-user-credentials:
    user1: pass1
    user2: pass2
    user3: pass3
data:
  csv:
    transactions-location: src/main/resources/transactions.csv
    fee-wages-location: src/main/resources/fee_wages.csv